### ISSUE TITLE
Use bot password or OAuth

### ISSUE THREAD

**Issue by Steinsplitter** [Toollabs/commons-maintenance-bot#1]
Adminbot should use a secure login methode.
https://commons.wikimedia.org/wiki/Commons:Bots/Secure_login

**Comment by Rillke** [comment]
> Adminbot should use a secure login methode.

I used a bot password since they were introduced. The password has now been reset. I would prefer OAuth but right now do not have the time to implement. Feel free to open a new issue for OAuth.

Also added this information to https://commons.wikimedia.org/wiki/Commons:Bots/Secure_login
